---
- hosts: localhost
  become: yes
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: Gather facts
      tags: production
      block:
        - name: Gather EC2 metadata facts
          ec2_metadata_facts:

        - name: list tags on instance
          ec2_tag:
            region: "{{ ansible_ec2_placement_region }}"
            resource: "{{ ansible_ec2_instance_id }}"
            state: list
          register: ec2_tags

        - name: Gather information about all regions
          aws_region_info: region={{ansible_ec2_placement_region}}
          register: aws_regions_info

 
    - name: setup role
          include_role:
            name: apache

